import Foundation

class LevelViewModel : ObservableObject {
    @Published var allLevels: [LevelModel] =
    [
        LevelModel(
            levelNum: 1,
            level: "level1_",
            answer: ["👽", "?", "?", "?", "?", "?"],
            answer2: ["👽", "?", "?", "?", "?", "?"],
            pickerXPos: [0.5],
            pickerYPos: [0.05],
            xPos: [0.8, 0.82, 0.5, 0.2, 0.2],
            yPos: [0.7, 0.15, 0.06, 0.16, 0.68],
            angles: [110, 50, 0, -50, -120],
            objective: "Hello, space traveller! I want you to collect as many 👽 as you need. Your finish spot is marked with 🏁, which, incidentally, is also your place of departure.",
            finishX: 0.5,
            finishY: 0.83),
        LevelModel(levelNum: 2,
                   level: "level2_",
                   answer: ["🌒", "👽", "🌒", "👽", "?", "?"],
                   answer2: ["🌒", "👽", "🌒", "👽", "?", "?"],
                   pickerXPos: [0.5, 0.93, 0.5, 0.06],
                   pickerYPos: [0.05, 0.5, 0.96, 0.5],
                   xPos: [0.7, 0.82, 0.5, 0.2, 0.2],
                   yPos: [0.676, 0.15, 0.06, 0.16, 0.68],
                   angles: [160, 50, 0, -50, -120],
                   objective: "Hello, space traveller! I want you to collect an odd number of 👽. Your finish spot is marked with 🏁.",
                   finishX: 0.5,
                   finishY: 0.28),
        
        LevelModel(levelNum: 3,
                   level: "level2_",
                   answer: ["🌒", "👽", "🌒", "👽", "?", "?"],
                   answer2: ["🌒", "👽", "🌒", "👽", "?", "?"],
                   pickerXPos: [0.5, 0.93, 0.5, 0.06],
                   pickerYPos: [0.05, 0.5, 0.96, 0.5],
                   xPos: [0.7, 0.82, 0.5, 0.2, 0.2],
                   yPos: [0.676, 0.15, 0.06, 0.16, 0.68],
                   angles: [160, 50, 0, -50, -120],
                   objective: "Hello, space traveller! I want you to collect an even number of 👽. Your finish spot is marked with 🏁.",
                   finishX: 0.5,
                   finishY: 0.7),
        
        LevelModel(levelNum: 4,
                   level: "level4_",
                   answer: ["👽", "👽", "👽", "🌒", "🌒", "🌒"],
                   answer2: ["🌒", "👽", "👽", "🌒", "🌒", "👽"],
                   pickerXPos: [0.5, 0.91, 0.88, 0.48, 0.1, 0.1],
                   pickerYPos: [0.05, 0.37, 0.67, 0.96, 0.63, 0.32],
                   xPos: [0.7, 0.82, 0.5, 0.2, 0.2],
                   yPos: [0.76, 0.15, 0.06, 0.16, 0.68],
                   angles: [160, 50, 0, -50, -120],
                   objective: "Hello, space traveller! In your travels, I want you to, at least once, gather 👽👽 consecutively. Your finish spot is marked with 🏁.",
                   finishX: 0.5,
                   finishY: 0.23)]
}
